import React, { useEffect, useState } from 'react';
import { ScrollView, View, StyleSheet } from 'react-native';
import Camera from './Camera';
import TypingAnimation from './TypingAnimation';

export default function App() {
  return (
    <ScrollView>  
     <View style={{marginTop: '22%', alignItems: 'center'}}>
   	<TypingAnimation text="Predict life expectancy." fontSize={24} animationSpeed={24}/>
     </View>
    <View style={{marginTop: '9%', alignItems: 'center'}}>
	<Camera/>
    </View>
     <View style={{marginTop: '8%', paddingHorizontal: '8%', alignItems: 'center'}}>
   	<TypingAnimation text="Disclaimer: This is experimental technology. It is not intended to provide, and should not be relied on for, any form of professional medical advice, diagnosis, or treatment. The life expectancy prediction generated by this application is based on algorithms and machine learning. Always seek the advice of your physician or other qualified health providers with any questions you may have regarding a medical condition or your health." fontSize={17} animationSpeed={10}/>
     </View>
	  <View style={{marginTop: '8%', alignItems: 'center'}}>
   	<TypingAnimation text="Submit feedback and ideas at thomasrialan@gmail.com" fontSize={17} animationSpeed={10}/>
	  </View>
    </ScrollView>
  );
}

